name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  workflow_dispatch:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 1、生成静态文件
      - name: Build
        run: npm install && npm run build

      # 2、部署到 GitHub Pages
      - name: Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PUBLISH_REPOSITORY: archks/archks.github.io
          BRANCH: main
          PUBLISH_DIR: ./public
          PERSONAL_TOKEN: ${{ secrets.BK_TOKEN }} 
        # uses: JamesIves/github-pages-deploy-action@releases/v3
        # with:
        #   BK_TOKEN: ${{ secrets.BK_TOKEN }}
        #   REPOSITORY_NAME: archks/archks.github.io
        #   BRANCH: main
        #   FOLDER: public
          #注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`

      # 3、刷新cdn
      - name: Refresh CDN
        run: |
          curl --location --request POST 'https://api.upyun.com/buckets/purge/batch' \
          --header 'Authorization: Bearer bcb60ea8-d653-4f4f-8baf-394d2c4c83b9' \
          --header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
          --header 'Content-Type: application/json' \
          --header 'Accept: */*' \
          --header 'Host: api.upyun.com' \
          --header 'Connection: keep-alive' \
          --data-raw '{
            "noif": 42,
            "delay": 42,
            "source_url": "https://ymlog.cn/*"
          }'